apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-app.fullname" . }}
  labels:
    app: {{ include "backend-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend-app.name" . }}
    spec:
      containers:
        - name: {{ include "backend-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            - name: DB
              value: {{ .Values.env.DB | quote }}

            - name: DB_HOST
              value: {{ printf "%s-postgresql-rw" .Release.Name | quote }}

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgresql-app" .Release.Name }}
                  key: username

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgresql-app" .Release.Name }}
                  key: password

          resources:
{{ toYaml .Values.resources | indent 12 }}